### ISSUE TITLE
Seeders - test2Fer

### ISSUE THREAD

**Issue by FerRB27** [KarlaRomero17/gestion-membresias-gimnasio#1]
- - No se crean los seeders para la clase de Area en los seeders/factory de tal Clase.
- - Nav bar solo configuurada para mostrarse y redirigir a 2 vistas (area y membership) no hay content aun
-

**Comment by FerRB27** [comment]
la linea 
 _$this->call(AreasTableSeeder::class);_
en el archivo database/seeders/DartaBaseSeeder.php
solvento el problema de los seeders en la tabla areas

**Comment by KarlaRomero17** [comment]
Gracias Fer
